### ISSUE TITLE
Whether this only works with templates or services as well

### ISSUE THREAD

**Issue by rahulsahay19** [urish/ng-lift#1]
Hi,

Thanks for writing this awesome plugin. Just wanted to check whether this works with templates only or services and controllers are also supported?

Thanks,
Rahul

**Comment by urish** [comment]
Right now, it only works with templates. I have some ideas about how to assist with upgrading services and controllers automatically, but I'm not sure if and when I will find time to implement them

**Comment by rahulsahay19** [comment]
Ok Np. Thanks!
